### ISSUE TITLE
Refactor git-download.sh for Improved Error Handling and Usability

### ISSUE THREAD

**Issue by Crusherbolt** [moebrowne/git-download#1]
1. Improve error handling: Add checks for errors after critical commands (e.g., git clone) to ensure the script exits gracefully in case of failure.
2. Enhance parameter validation: Validate input parameters more robustly, including checking for required arguments and providing meaningful error messages.
3. Add a usage/help function: Implement a usage function to display help information, including examples of how to use the script.
4. Improve user interaction: Prompt the user to confirm if an existing download directory should be overwritten.
5. Cross-platform compatibility: Use command -v to check for the presence of Git, making the script more portable.
6. Remove unnecessary .git directory: Automatically clean up the downloaded content by removing the .git directory.

**Comment by Crusherbolt** [comment]
@moebrowne I would like to make git-download.sh better

**Comment by moebrowne** [comment]
@Crusherbolt I think you solved all the issues in #2. Feel free to re-open if not.

Thanks for the contribution!
